// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calib
Rcpp::List calib(arma::vec theta1, arma::mat theta2, arma::cube theta3, arma::vec theta, int n, int p, int B1, int B2, int B3, double B10, double B20, double B30);
RcppExport SEXP _GBS_calib(SEXP theta1SEXP, SEXP theta2SEXP, SEXP theta3SEXP, SEXP thetaSEXP, SEXP nSEXP, SEXP pSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B3SEXP, SEXP B10SEXP, SEXP B20SEXP, SEXP B30SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta1(theta1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type theta3(theta3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< int >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< int >::type B3(B3SEXP);
    Rcpp::traits::input_parameter< double >::type B10(B10SEXP);
    Rcpp::traits::input_parameter< double >::type B20(B20SEXP);
    Rcpp::traits::input_parameter< double >::type B30(B30SEXP);
    rcpp_result_gen = Rcpp::wrap(calib(theta1, theta2, theta3, theta, n, p, B1, B2, B3, B10, B20, B30));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GBS_calib", (DL_FUNC) &_GBS_calib, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_GBS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
