# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calib <- function(theta1, theta2, theta3, theta, n, p, B1, B2, B3, B10, B20, B30) {
    .Call(`_GBS_calib`, theta1, theta2, theta3, theta, n, p, B1, B2, B3, B10, B20, B30)
}

